/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FunnelRouteImport } from './routes/funnel'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as IndexRouteImport } from './routes/index'

const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelRoute = FunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/debug': typeof DebugRoute
  '/decisions': typeof DecisionsRoute
  '/funnel': typeof FunnelRoute
  '/health': typeof HealthRoute
  '/holdings': typeof HoldingsRoute
  '/performance': typeof PerformanceRoute
  '/supervisor': typeof SupervisorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/debug': typeof DebugRoute
  '/decisions': typeof DecisionsRoute
  '/funnel': typeof FunnelRoute
  '/health': typeof HealthRoute
  '/holdings': typeof HoldingsRoute
  '/performance': typeof PerformanceRoute
  '/supervisor': typeof SupervisorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/debug': typeof DebugRoute
  '/decisions': typeof DecisionsRoute
  '/funnel': typeof FunnelRoute
  '/health': typeof HealthRoute
  '/holdings': typeof HoldingsRoute
  '/performance': typeof PerformanceRoute
  '/supervisor': typeof SupervisorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/costs'
    | '/debug'
    | '/decisions'
    | '/funnel'
    | '/health'
    | '/holdings'
    | '/performance'
    | '/supervisor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/costs'
    | '/debug'
    | '/decisions'
    | '/funnel'
    | '/health'
    | '/holdings'
    | '/performance'
    | '/supervisor'
  id:
    | '__root__'
    | '/'
    | '/costs'
    | '/debug'
    | '/decisions'
    | '/funnel'
    | '/health'
    | '/holdings'
    | '/performance'
    | '/supervisor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CostsRoute: typeof CostsRoute
  DebugRoute: typeof DebugRoute
  DecisionsRoute: typeof DecisionsRoute
  FunnelRoute: typeof FunnelRoute
  HealthRoute: typeof HealthRoute
  HoldingsRoute: typeof HoldingsRoute
  PerformanceRoute: typeof PerformanceRoute
  SupervisorRoute: typeof SupervisorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnel': {
      id: '/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof FunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CostsRoute: CostsRoute,
  DebugRoute: DebugRoute,
  DecisionsRoute: DecisionsRoute,
  FunnelRoute: FunnelRoute,
  HealthRoute: HealthRoute,
  HoldingsRoute: HoldingsRoute,
  PerformanceRoute: PerformanceRoute,
  SupervisorRoute: SupervisorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
